package clases;

import java.awt.event.KeyEvent;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

public class consultabasedatos extends javax.swing.JFrame implements Observer {

    public consultabasedatos() {
        initComponents();
        servidor s = new servidor(6000); //se crea el objeto del servidor
        s.addObserver(this);//aqui tienes que colocar a quien vas a notificar no borrar importante
        Thread t = new Thread(s);//un hilo que le pasaremos el servidor
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        basedato = new javax.swing.JComboBox<>();
        tablas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txt_dato = new javax.swing.JTextField();
        nom_tab = new javax.swing.JComboBox<>();
        salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        basedato2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tablas1 = new javax.swing.JComboBox<>();
        nom_tab1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_dato1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tablas2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_dato2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        chats = new javax.swing.JTextArea();
        cconsulta1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nom_tab2 = new javax.swing.JComboBox<>();
        salir1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        basedato1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        basedato3 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tablas3 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        nom_tab3 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txt_dato3 = new javax.swing.JTextField();
        Eliminar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_texto_enviar = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)), "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basedato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        basedato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "base de datos 1", "base de datos 2", "base de datos 3" }));
        jPanel1.add(basedato, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 107, -1, -1));

        tablas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tabla 1", "productos", "Tabla 3", "Tabla 4" }));
        jPanel1.add(tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 104, 185, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Donde id =");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 102, 98, 38));

        txt_dato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_dato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_datoKeyPressed(evt);
            }
        });
        jPanel1.add(txt_dato, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 107, 188, -1));

        nom_tab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nom_tab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre de la tablas 1", "idProducto", "Nombre de la tablas 3", "Nombre de la tablas 4" }));
        jPanel1.add(nom_tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 102, 228, 37));

        salir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salir.setText("Salir");
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 30, 90, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Eliminación");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel8.setText("Base de datos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        basedato2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        basedato2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "base de datos 2", "base de datos 3" }));
        jPanel1.add(basedato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        jLabel9.setText("Nombre de la tabla");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        tablas1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "productos", "Tabla 3", "Tabla 4" }));
        jPanel1.add(tablas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 185, 35));

        nom_tab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nom_tab1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "idProducto", "Nombre de la tablas 3", "Nombre de la tablas 4" }));
        jPanel1.add(nom_tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 228, 37));

        jLabel10.setText("Nombre de la columna");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Donde id =");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 98, 38));

        txt_dato1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_dato1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dato1KeyPressed(evt);
            }
        });
        jPanel1.add(txt_dato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 188, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)), "Consulta y eliminacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablas2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "productos", "Tabla 3", "Tabla 4" }));
        jPanel3.add(tablas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 104, 185, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Donde id =");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 102, 98, 38));

        txt_dato2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_dato2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dato2KeyPressed(evt);
            }
        });
        jPanel3.add(txt_dato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 107, 188, -1));

        chats.setColumns(20);
        chats.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        chats.setRows(5);
        jScrollPane2.setViewportView(chats);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 1080, 380));

        cconsulta1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cconsulta1.setText("Consulta");
        cconsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cconsulta1ActionPerformed(evt);
            }
        });
        jPanel3.add(cconsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 102, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Resultado ------>");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        nom_tab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nom_tab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "idProducto", "Nombre de la tablas 3", "Nombre de la tablas 4" }));
        jPanel3.add(nom_tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 102, 228, 37));

        salir1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salir1.setText("Salir");
        jPanel3.add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2090, 40, 90, 50));

        jLabel5.setText("Base de datos");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setText("Nombre de la tabla");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel12.setText("Nombre de la columna");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Eliminación");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Consulta");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        basedato1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        basedato1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "base de datos 2", "base de datos 3" }));
        jPanel3.add(basedato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 107, -1, 30));

        jLabel15.setText("Base de datos");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        basedato3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        basedato3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "base de datos 2", "base de datos 3" }));
        jPanel3.add(basedato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        jLabel16.setText("Nombre de la tabla");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        tablas3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablas3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "productos", "Tabla 3", "Tabla 4" }));
        jPanel3.add(tablas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 185, 35));

        jLabel17.setText("Nombre de la columna");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        nom_tab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nom_tab3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "idProducto", "Nombre de la tablas 3", "Nombre de la tablas 4" }));
        jPanel3.add(nom_tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 228, 37));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Donde id =");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 98, 38));

        txt_dato3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_dato3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dato3KeyPressed(evt);
            }
        });
        jPanel3.add(txt_dato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 188, -1));

        Eliminar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 200, 130, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Editar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 510, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 1638, -1));

        txt_texto_enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_texto_enviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_texto_enviarKeyPressed(evt);
            }
        });
        getContentPane().add(txt_texto_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 721, 1600, 48));

        enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1619, 730, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_datoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_datoKeyPressed
        //para que de enter se salte a continuar

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            if (!txt_dato.getText().trim().equals("")) {
                cconsulta1.requestFocus();
                cconsulta1.doClick();
                txt_dato.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo en necesario");
            }
        }
    }//GEN-LAST:event_txt_datoKeyPressed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        String mensaje = "\n" + "bebidas: " + this.txt_texto_enviar.getText() + "\n";//se guarda el mensaje en variable
        this.chats.append(mensaje);//se coloca el mensaje en la conversacion
        //las siguientes lineas manda mensaje al servidor
        cliente c = new cliente(5000, mensaje);
        Thread t = new Thread(c);
        t.start();
        this.txt_texto_enviar.setText("");
    }//GEN-LAST:event_enviarActionPerformed

    private void txt_texto_enviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_texto_enviarKeyPressed
        //para que de enter se salte a continuar

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            if (!txt_texto_enviar.getText().trim().equals("")) {
                enviar.requestFocus();
                enviar.doClick();
                txt_texto_enviar.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo en necesario");
            }
        }
    }//GEN-LAST:event_txt_texto_enviarKeyPressed

    private void txt_dato1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dato1KeyPressed
        //para que de enter se salte a continuar

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            if (!txt_dato1.getText().trim().equals("")) {
                enviar.requestFocus();
                enviar.doClick();
                txt_dato1.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo en necesario");
            }
        }
    }//GEN-LAST:event_txt_dato1KeyPressed

    private void txt_dato2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dato2KeyPressed
        //para que de enter se salte a continuar

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            if (!txt_dato.getText().trim().equals("")) {
                cconsulta1.requestFocus();
                cconsulta1.doClick();
                txt_dato.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo en necesario");
            }
        }
    }//GEN-LAST:event_txt_dato2KeyPressed

    private void cconsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cconsulta1ActionPerformed
        String base = (String) basedato1.getSelectedItem();
        System.out.println(base);
        String tab = (String) tablas.getSelectedItem();
        String d = txt_dato.getText().trim();
        System.out.println(tablas);
        System.out.println(d);
        String nombretabla = (String) nom_tab.getSelectedItem();

        String sql = "SELECT * FROM " + tab + " WHERE " + nombretabla + " = '" + d + " '";
        System.out.println(sql);
        //chats.append(sql);
        Servidor_cliente ng = new Servidor_cliente();
        String mm = ng.getMenss(sql);
        chats.append("\n" + mm);
        //modificacion
        cliente c = new cliente(5000, sql);
        Thread t = new Thread(c);
        t.start();
    }//GEN-LAST:event_cconsulta1ActionPerformed

    private void txt_dato3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dato3KeyPressed
        //para que de enter se salte a continuar

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            if (!txt_dato1.getText().trim().equals("")) {
                enviar.requestFocus();
                enviar.doClick();
                txt_dato1.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo en necesario");
            }
        }
    }//GEN-LAST:event_txt_dato3KeyPressed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        String base = (String) basedato2.getSelectedItem();
        System.out.println(base);
        String tab = (String) tablas1.getSelectedItem();
        String d = txt_dato1.getText().trim();
        System.out.println(tablas1);
        System.out.println(d);
        String nombretabla = (String) nom_tab1.getSelectedItem();

        String sql = "DELETE FROM " + tab + " WHERE " + nombretabla + " = '" + d + " '";
        System.out.println(sql);
        //chats.append(sql);
        Servidor_cliente ng = new Servidor_cliente();
        String mm = ng.getMenss(sql);
        chats.append("\n" + mm);
        //modificacion
        cliente c = new cliente(5000, sql);
        Thread t = new Thread(c);
        t.start();
    }//GEN-LAST:event_Eliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultabasedatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultabasedatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultabasedatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultabasedatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultabasedatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar1;
    private javax.swing.JComboBox<String> basedato;
    private javax.swing.JComboBox<String> basedato1;
    private javax.swing.JComboBox<String> basedato2;
    private javax.swing.JComboBox<String> basedato3;
    private javax.swing.JButton cconsulta1;
    private javax.swing.JTextArea chats;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> nom_tab;
    private javax.swing.JComboBox<String> nom_tab1;
    private javax.swing.JComboBox<String> nom_tab2;
    private javax.swing.JComboBox<String> nom_tab3;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JComboBox<String> tablas;
    private javax.swing.JComboBox<String> tablas1;
    private javax.swing.JComboBox<String> tablas2;
    private javax.swing.JComboBox<String> tablas3;
    private javax.swing.JTextField txt_dato;
    private javax.swing.JTextField txt_dato1;
    private javax.swing.JTextField txt_dato2;
    private javax.swing.JTextField txt_dato3;
    private javax.swing.JTextField txt_texto_enviar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.chats.append((String) arg);
    }
}
