/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Wendy
 */
public class Empleado_Modifica extends javax.swing.JInternalFrame {

    /**
     * Creates new form Empleado_Modifica
     */
    public Empleado_Modifica() {
        initComponents();
        Tablas x = new Tablas();
        x.verEmpleados(tabla, "");
    }
    int codigo = 0;
    
    public void modifica(int id,String nombre, String direccion, String telefono, String rfc){
        SetGet_Empleados vo = new SetGet_Empleados();
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        
        vo.setIdEmpleado(id);
        vo.setNombre(nombre);
        vo.setDireccion(direccion);
        vo.setTelefono(telefono);
        vo.setRFC(rfc);
        
        cc.modificaEmpleado(vo);
    }

//    public void modificar(int id,String nombre, String telefono, String ciudad, String direccion, String sexo,String ruta, File imagen){
//        SetGet_Empleados vo = new SetGet_Empleados();
//        Conectar cc = new Conectar();
//        Connection cn = cc.conexion();
//        
//        vo.setID(id);
//        vo.setNombre(nombre);
//        vo.setTelefono(telefono);
//        vo.setCiudad(ciudad);
//        vo.setDireccion(direccion);
//        vo.setSexo(sexo);
//        vo.setRutaImagen(ruta);
//        
//        try{
//            byte[] icono = new byte[(int) imagen.length()];
//            InputStream input = new FileInputStream(imagen);
//            input.read(icono);
//            vo.setFoto(icono);
//        }catch(Exception ex){
//            vo.setFoto(null);
//        }
//        cc.modificaEmpleado1(vo);
//    }
//    
//    public void modificar2(int id,String nombre, String telefono, String ciudad, String direccion, String sexo){
//        SetGet_Empleados vo = new SetGet_Empleados();
//        Conectar cc = new Conectar();
//        Connection cn = cc.conexion();
//        
//        vo.setID(id);
//        vo.setNombre(nombre);
//        vo.setTelefono(telefono);
//        vo.setCiudad(ciudad);
//        vo.setDireccion(direccion);
//        vo.setSexo(sexo);
//
//        cc.modificaEmpleado2(vo);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtdirec = new javax.swing.JTextField();
        txtcel = new javax.swing.JTextField();
        txtrfc = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        grabar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modifica los datos de un empleado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 570, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        jLabel1.setText("Datos del Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(255, 204, 204));
        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 139, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        txtnom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 139, -1));

        txtdirec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtdirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 139, -1));

        txtcel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 139, -1));

        txtrfc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtrfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 139, -1));

        limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 91, -1));

        grabar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grabar.setText("Actualizar");
        grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarActionPerformed(evt);
            }
        });
        getContentPane().add(grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salir.setText("Regresar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 91, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("RFC");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dulcesdeliciasadsasda.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 140, 120));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int clic = tabla.rowAtPoint(evt.getPoint());

        codigo = (int)tabla.getValueAt(clic, 0);
        String nombre = ""+tabla.getValueAt(clic, 1);
        String direccion = ""+tabla.getValueAt(clic, 2);
        String telefono = ""+tabla.getValueAt(clic, 3);
        String rfc = ""+tabla.getValueAt(clic, 4);

        txtid.setText(String.valueOf(codigo));
        txtnom.setText(nombre);
        txtdirec.setText(direccion);
        txtcel.setText(telefono);
        txtrfc.setText(rfc);
       
    }//GEN-LAST:event_tablaMouseClicked

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtnom.setText("");
        txtdirec.setText("");
        txtcel.setText("");
        txtrfc.setText("");
 
    }//GEN-LAST:event_limpiarActionPerformed

    private void grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarActionPerformed
        // TODO add your handling code here:
        Tablas xD = new Tablas();
        int id = Integer.parseInt(txtid.getText());
        String nombre = txtnom.getText();
        String direccion = txtdirec.getText();
        String telefono = txtcel.getText();
        String rfc = txtrfc.getText();
        this.modifica(id, nombre, direccion, telefono, rfc);
        Tablas x = new Tablas();
        x.verEmpleados(tabla, "");
    }//GEN-LAST:event_grabarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton grabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtcel;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtrfc;
    // End of variables declaration//GEN-END:variables
}
