/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.JOptionPane;

/**
 *
 * @author Wendy
 */
public class Empleado_Consulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Empleado_Consulta
     */
    public Empleado_Consulta() {
        initComponents();
        Tablas xdd = new Tablas();
        xdd.verEmpleados(tabla,"");
        int total = xdd.verEmpleados(tabla, "");
    }

    int totalx = 0;
    
    
    public int total(){
        Tablas xd = new Tablas();
        this.totalx = xd.verEmpleados(tabla, "");
        return this.totalx;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        verTablaxd = new javax.swing.JButton();
        total = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta los datos del empleado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 550, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        txtbuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 85, -1));

        buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscar.setText("Busca");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 160, -1));

        verTablaxd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verTablaxd.setText("Ver Tabla");
        verTablaxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTablaxdActionPerformed(evt);
            }
        });
        getContentPane().add(verTablaxd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 160, -1));

        total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total.setText("Total de Empleados");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 160, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit.setText("Regresar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dulcesdeliciasadsasda.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 140, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f6.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 790, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        Tablas xD = new Tablas();
        String x = txtbuscar.getText();
        int busca = Integer.parseInt(txtbuscar.getText());
        int cont = xD.verEmpleados(tabla, "");
        if(busca <= cont)
            xD.verEmpleados(tabla, x);
        else
            JOptionPane.showMessageDialog(null, "El empleado no existe");
    }//GEN-LAST:event_buscarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        txtbuscar.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void verTablaxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTablaxdActionPerformed
        // TODO add your handling code here:
        Tablas xd = new Tablas();
        xd.verEmpleados(tabla, "");
    }//GEN-LAST:event_verTablaxdActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        Tablas xd = new Tablas();
        this.totalx = xd.verEmpleados(tabla, "");
        JOptionPane.showMessageDialog(null, "El total de empleados es de: "+totalx+" personas.");
    }//GEN-LAST:event_totalActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTable tabla;
    private javax.swing.JButton total;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JButton verTablaxd;
    // End of variables declaration//GEN-END:variables
}
