/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.sql.Connection;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Wendy
 */
public class Empleado_Pagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Empleado_Pagos
     */
    public Empleado_Pagos() {
        initComponents();
        Tablas xd = new Tablas();
        xd.verPagos(tabla, "");
        
    }
    int codigo = 0;
    int total = 0;

    public void guardarPago(int pago, int empleado, String fecha, int monto, int hrs){
        SetGet_Pagos vo = new SetGet_Pagos();
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        
        vo.setIdPago(pago);
        vo.setidEmpleado(empleado);
        vo.setfecha(fecha);
        vo.setIdmonto(monto);
        vo.sethorasExtras(hrs);
        
        cc.guardaPago(vo);
    }
    
    public String convertir(Date date){
        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        return formatter.format(date);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtpago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtempleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txthrs = new javax.swing.JTextField();
        txtfecha = new com.toedter.calendar.JDateChooser();
        grabar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar un nuevo pago");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Detalles del pago");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 11, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 557, 343));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Pago");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 52, -1, -1));

        txtpago.setBackground(new java.awt.Color(255, 204, 204));
        txtpago.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 49, 134, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID Empleado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 84, -1, -1));

        txtempleado.setBackground(new java.awt.Color(255, 204, 204));
        txtempleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 81, 134, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 113, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Monto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 142, -1, -1));

        txtmonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 139, 134, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Horas Extra");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 174, -1, -1));

        txthrs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txthrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 171, 133, -1));
        getContentPane().add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 113, 134, -1));

        grabar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grabar.setText("Grabar");
        grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarActionPerformed(evt);
            }
        });
        getContentPane().add(grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 215, 85, -1));

        limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 262, 85, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit.setText("Regresar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 325, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dulcesdeliciasadsasda.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 130, 120));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f8.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-680, -200, 1530, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagoActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
//        int clic = tabla.rowAtPoint(evt.getPoint());
//        codigo = (int)tabla.getValueAt(clic, 0);
//        txtpago.setText(String.valueOf(codigo));
//        String empleado = ""+tabla.getValueAt(clic, 1);
//        String fecha = ""+tabla.getValueAt(clic, 2);
//        String monto = ""+tabla.getValueAt(clic, 3);
//        String hrs = ""+tabla.getValueAt(clic, 4);
//
//        txtempleado.setText(empleado);
//        txtmonto.setText(monto);
//        txthrs.setText(hrs);
        
    }//GEN-LAST:event_tablaMouseClicked

    private void grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarActionPerformed
        // TODO add your handling code here:
        int pago = Integer.parseInt(txtpago.getText());
        int empelado = Integer.parseInt(txtempleado.getText());
        Date f = txtfecha.getDate();
        int monto = Integer.parseInt(txtmonto.getText());
        String horas = txthrs.getText();
        int hrs = Integer.parseInt(horas);
        String fecha = convertir(f);
        
        this.guardarPago(pago, empelado, fecha, monto, hrs);
        Tablas xd = new Tablas();
        xd.verPagos(tabla, "");
    }//GEN-LAST:event_grabarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        txtpago.setText("");
        txtempleado.setText("");
        txtfecha.setDate(null);
        txtmonto.setText("");
        txthrs.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton grabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtempleado;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txthrs;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtpago;
    // End of variables declaration//GEN-END:variables
}
