/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Wendy
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        escritorio.setBorder(new ImagenFondo());
        this.setExtendedState(menu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        inventario = new javax.swing.JMenu();
        inserta = new javax.swing.JMenuItem();
        modifica = new javax.swing.JMenuItem();
        elimina = new javax.swing.JMenuItem();
        consulta = new javax.swing.JMenuItem();
        empleados = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        Ventas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        escritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 747, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 422, Short.MAX_VALUE))
        );

        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconInventario.png"))); // NOI18N
        inventario.setText("Inventario Productos");
        inventario.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N

        inserta.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        inserta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/insertaIcono.png"))); // NOI18N
        inserta.setText("Insertar Nuevo");
        inserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaActionPerformed(evt);
            }
        });
        inventario.add(inserta);

        modifica.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        modifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IconoEditar.png"))); // NOI18N
        modifica.setText("Modifica");
        modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaActionPerformed(evt);
            }
        });
        inventario.add(modifica);

        elimina.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        elimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminaIcono.png"))); // NOI18N
        elimina.setText("Elimina");
        elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaActionPerformed(evt);
            }
        });
        inventario.add(elimina);

        consulta.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscaInventario.png"))); // NOI18N
        consulta.setText("Consulta");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        inventario.add(consulta);

        jMenuBar1.add(inventario);

        empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empleadoIcono.png"))); // NOI18N
        empleados.setText("Empleados");
        empleados.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/insertaIcono.png"))); // NOI18N
        jMenuItem12.setText("Nuevo Empleado");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        empleados.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/insertaIcono.png"))); // NOI18N
        jMenuItem13.setText("Nuevo pago ");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        empleados.add(jMenuItem13);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IconoEditar.png"))); // NOI18N
        jMenu4.setText("Modificar");
        jMenu4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconInventario.png"))); // NOI18N
        jMenuItem14.setText("Información del empleado");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        empleados.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminaIcono.png"))); // NOI18N
        jMenu5.setText("Elimina");
        jMenu5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empleadoIcono.png"))); // NOI18N
        jMenuItem16.setText("Empleado");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        empleados.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscaInventario.png"))); // NOI18N
        jMenu6.setText("Consulta");
        jMenu6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empleadoIcono.png"))); // NOI18N
        jMenuItem18.setText("Empleados");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconInventario.png"))); // NOI18N
        jMenuItem20.setText("Pagos ");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        empleados.add(jMenu6);

        jMenuBar1.add(empleados);

        Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ventasIcono.png"))); // NOI18N
        Ventas.setText("Ventas");
        Ventas.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventasIcono.png"))); // NOI18N
        jMenuItem1.setText("Nueva Venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Ventas.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconInventario.png"))); // NOI18N
        jMenuItem4.setText("Pedidos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Ventas.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificaIcono.png"))); // NOI18N
        jMenuItem6.setText("Corte de caja");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Ventas.add(jMenuItem6);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconInventario.png"))); // NOI18N
        jMenuItem8.setText("Inventario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Ventas.add(jMenuItem8);

        jMenuBar1.add(Ventas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaActionPerformed
        // TODO add your handling code here:
        Producto_Inserta xD = new Producto_Inserta();
        escritorio.add(xD);
        xD.show();
    }//GEN-LAST:event_insertaActionPerformed

    private void modificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaActionPerformed
        // TODO add your handling code here:
        Producto_Modifica xD = new Producto_Modifica();
        escritorio.add(xD);
        xD.show();
    }//GEN-LAST:event_modificaActionPerformed

    private void eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaActionPerformed
        // TODO add your handling code here:
        Producto_Elimina xD = new Producto_Elimina();
        escritorio.add(xD);
        xD.show();
    }//GEN-LAST:event_eliminaActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
        Producto_Consulta xd = new Producto_Consulta();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_consultaActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        Empleado_Inserta xd = new Empleado_Inserta();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        Empleado_Pagos xd = new Empleado_Pagos();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        Empleado_Modifica xd = new Empleado_Modifica();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        Empleado_Elimina xd = new Empleado_Elimina();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        Empleado_Consulta xd = new Empleado_Consulta();
        escritorio.add (xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        Empleado_PagoConsulta xd = new Empleado_PagoConsulta();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?","Mensaje",JOptionPane.OK_CANCEL_OPTION);
        if (a == 0){
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Venta xd = new Venta();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Pedidos xd = new Pedidos();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/cortedecaja.pdf"));
            documento.open();

            PdfPTable tabla = new PdfPTable(4);
            tabla.addCell("ID venta");
            tabla.addCell("ID producto");
            tabla.addCell("ID pedido");
            tabla.addCell("Total de la venta");

            try {
                conectar cc = new conectar();
                Connection cn = cc.conexion();
                PreparedStatement pst = cn.prepareStatement("SELECT * FROM ventas");

                ResultSet r = pst.executeQuery();

                if (r.next()) {
                    do {
                        tabla.addCell(r.getString(1));
                        tabla.addCell(r.getString(2));
                        tabla.addCell(r.getString(3));
                        tabla.addCell(r.getString(4));
                    } while (r.next());
                    documento.add(tabla);
                } else {
                    JOptionPane.showMessageDialog(null, "sin ventas");
                }
            } catch (DocumentException | HeadlessException | SQLException e) {

            }
            documento.close();
            JOptionPane.showMessageDialog(null, "corte de caja de hoy en dia hecho");
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {

        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        inventario xd = new inventario();
        escritorio.add(xd);
        xd.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ventas;
    private javax.swing.JMenuItem consulta;
    private javax.swing.JMenuItem elimina;
    private javax.swing.JMenu empleados;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem inserta;
    private javax.swing.JMenu inventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem modifica;
    // End of variables declaration//GEN-END:variables
}
