/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Wendy
 */
public class Producto_Elimina extends javax.swing.JInternalFrame {

    /**
     * Creates new form Producto_Elimina
     */
    public Producto_Elimina() {
        initComponents();
        Tablas xD = new Tablas();
        xD.verProductos(tabla, "");
    }
    
    int cod = 0;

    public void eliminar(int id){
        SetGet_Productos vo = new SetGet_Productos();
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        
        vo.setIdProducto(cod);
        
        cc.Eliminar_Producto(vo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        elimina = new javax.swing.JButton();
        verTabla = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Elimina un producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 488, 460));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        txtbuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 92, -1));

        buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        elimina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        elimina.setText("Elimina");
        elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaActionPerformed(evt);
            }
        });
        getContentPane().add(elimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 125, -1));

        verTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verTabla.setText("Actualizar tabla");
        verTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTablaActionPerformed(evt);
            }
        });
        getContentPane().add(verTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit.setText("Regresar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 125, -1));

        limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 125, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dulcesdeliciasadsasda.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondooxD1.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -10, 760, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void verTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTablaActionPerformed
        // TODO add your handling code here:
        Tablas xd = new Tablas();
        xd.verProductos(tabla, "");
    }//GEN-LAST:event_verTablaActionPerformed

    private void eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtbuscar.getText());
        int a = JOptionPane.showConfirmDialog(null, "Desea eliminar este producto","Mensaje",JOptionPane.OK_CANCEL_OPTION);
        if(a == 0){
            this.eliminar(id);
        }
        Tablas xD = new Tablas();
        xD.verProductos(tabla, "");
    }//GEN-LAST:event_eliminaActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        txtbuscar.setText("");
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int clic = tabla.rowAtPoint(evt.getPoint());
        
        cod = (int)tabla.getValueAt(clic, 0);
        txtbuscar.setText(String.valueOf(cod));
    }//GEN-LAST:event_tablaMouseClicked

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String idproducto = "", idd = txtbuscar.getText();
        Pattern pat = Pattern.compile("[0-9]");
        Matcher mat = pat.matcher(txtbuscar.getText());
        if (mat.matches()) {
            try {
                conectar cc = new conectar();
                Connection cn = cc.conexion();
                PreparedStatement pst = cn.prepareStatement("SELECT * FROM productos where idProducto=?");
                pst.setString(1, txtbuscar.getText());
                ResultSet r = pst.executeQuery();
                if (r.next()) {
                    idproducto = r.getString("idProducto");
                } else {

                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en la conexion de base de datos");
            }
            if (!idproducto.equals(idd)) {
                JOptionPane.showMessageDialog(null, "Error la id del producto no esta registrada");
            } else {
                if (idd.equals("")) {
                    JOptionPane.showMessageDialog(null, "Espacio en blanco");
                    // }else{ 
                    //this.agregar(id, nombre, precio, categoria, fecha, imagen);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "En el campo id solo numeros por favor");
        }
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton elimina;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JButton verTabla;
    // End of variables declaration//GEN-END:variables
}
