/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Wendy
 */
public class Producto_Inserta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Producto_Inserta
     */
    public Producto_Inserta() {
        initComponents();
        Tablas xd = new Tablas();
        xd.verProductos(tabla, "");
        
    }
    public void agregar(int id, String nombre, int precio, String fecha, File imagen) {
        String llave = "", primaria = "";
        llave = txtid.getText();

        try {
            conectar cc = new conectar();
            Connection cn = cc.conexion();
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM productos where idProducto=?");
            pst.setString(1, txtid.getText());
            ResultSet r = pst.executeQuery();

            if (r.next()) {
                primaria = r.getString("idProducto");
            } else {
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
        if (llave.equals(primaria)) {
            JOptionPane.showMessageDialog(null, "Error numero de id repetido");

        } else {

            SetGet_Productos vo = new SetGet_Productos();
            conectar cc = new conectar();
            Connection cn = cc.conexion();

            vo.setIdProducto(id);
            vo.setNombreProducto(nombre);
            vo.setPrecioUnitario(precio);
            vo.setFecha(fecha);

            try {
                byte[] icono = new byte[(int) imagen.length()];
                InputStream input = new FileInputStream(imagen);
                input.read(icono);
                vo.setFoto(icono);
            } catch (Exception ex) {
                vo.setFoto(null);
            }
            cc.guardaProductos(vo);
            Tablas xd = new Tablas();
            xd.verProductos(tabla, "");
        }

    }
//    public void agregar(int id,String nombre, int precio, String categoria,String fecha, File imagen){
//        SetGet_Productos vo = new SetGet_Productos();
//        conectar cc = new conectar();
//        Connection cn = cc.conexion();
//        
//        vo.setIdProducto(id);
//        vo.setNombreProducto(nombre);
//        vo.setPrecioUnitario(precio);
//        vo.setCategoria(categoria);
//        vo.setFecha(fecha);
//        
//        try{
//            byte[] icono = new byte[(int) imagen.length()];
//            InputStream input = new FileInputStream(imagen);
//            input.read(icono);
//            vo.setFoto(icono);
//        }catch(Exception ex){
//            vo.setFoto(null);
//        }
//        cc.guardaProductos(vo);
//        Tablas xd = new Tablas();
//        xd.verProductos(tabla, "");
//    }
    
    public void compruebacampollave(int id){
        SetGet_Productos vo = new SetGet_Productos();
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        grabar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        seleccionar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtfecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtruta = new javax.swing.JLabel();
        lbimagen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingresa un nuevo producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        jLabel1.setText("Detalles del producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("idProducto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        txtid.setBackground(new java.awt.Color(255, 204, 204));
        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 56, 176, -1));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 88, 176, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, -1, -1));

        txtprecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 120, 176, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Imagen");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        grabar.setBackground(new java.awt.Color(204, 255, 204));
        grabar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grabar.setText("Grabar");
        grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarActionPerformed(evt);
            }
        });
        getContentPane().add(grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 90, -1));

        limpiar.setBackground(new java.awt.Color(204, 255, 204));
        limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 90, 30));

        exit.setBackground(new java.awt.Color(204, 255, 204));
        exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit.setText("Regresar ");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        seleccionar.setBackground(new java.awt.Color(204, 255, 204));
        seleccionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seleccionar.setText("Seleccionar");
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 70, 80));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 480, 422));

        txtfecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 176, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Fecha cad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtruta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 224, 210, 21));
        getContentPane().add(lbimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 200, 169));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dulcesdeliciasadsasda.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 140, 120));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondooxD1.jpeg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 0, 1330, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Tablas xd = new Tablas();
        xd.verProductos(tabla, "");
    }//GEN-LAST:event_exitActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        txtfecha.setText("");
        txtid.setText("");
        txtnombre.setText("");
        txtprecio.setText("");
        lbimagen.setText("");
        txtruta.setText("");
        lbimagen.setIcon(null);
    }//GEN-LAST:event_limpiarActionPerformed

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        j.setFileFilter(fil);
        
        int s = j.showOpenDialog(this);
        if(s == JFileChooser.APPROVE_OPTION){
            String ruta = j.getSelectedFile().getAbsolutePath();
            txtruta.setText(ruta);
            
            Image imagen = getToolkit().getImage(txtruta.getText());
            imagen = imagen.getScaledInstance(lbimagen.getWidth(), lbimagen.getHeight(), Image.SCALE_DEFAULT);
            lbimagen.setIcon(new ImageIcon(imagen));
        }
    }//GEN-LAST:event_seleccionarActionPerformed

    private void grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtid.getText());
        String nombre = txtnombre.getText();
        int precio = Integer.parseInt(txtprecio.getText());
        String fecha = txtfecha.getText();
        File imagen = new File(txtruta.getText());
        
        this.agregar(id, nombre, precio, fecha, imagen);
        //JOptionPane.showMessageDialog(null, "Este producto ya se encuentra en existencia");
        
    }//GEN-LAST:event_grabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton grabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbimagen;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton seleccionar;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JLabel txtruta;
    // End of variables declaration//GEN-END:variables
}
